# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/system.xdc

# IP: ip/Clk_Division_0/Clk_Division_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Clk_Division_0 || ORIG_REF_NAME==Clk_Division_0} -quiet] -quiet

# IP: ip/Clk_Division_1/Clk_Division_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Clk_Division_1 || ORIG_REF_NAME==Clk_Division_1} -quiet] -quiet
